### PR TITLE
[Android] Fix `require(...)` file resource on production

### LINKED ISSUE #338: Android - Video is not playing on release apk
RN 0.34
Using asset system (`source={require('../path/to/video.mp4')}`)
Working great on iOS and Android debug (`app-debug.apk`)
But not working on Android release APK

Any thoughts?

### PR DESCRIPTION
**Pull request by jhen0409**
Fix #338.

Should use `drawable` instead of `raw` for `setRawData`, see [`ResourceDrawableIdHelper` of react-native Image](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/imagehelper/ResourceDrawableIdHelper.java#L54-L57) usage. ([getAssetDestPathAndroid.js](https://github.com/facebook/react-native/blob/24d2bbfbab174aa528aa73cccbbefb67f95c2451/local-cli/bundle/getAssetDestPathAndroid.js))

Build the [example](https://github.com/react-native-community/react-native-video/tree/master/example) release apk and use [Apktool](https://github.com/iBotPeaches/Apktool) decode, can be simply seen:

### CODE REVIEW

**Comment by el-lsan** [comment]
@jhen0409 I tried your solution, but I'm still getting the same error:
`W/MediaPlayer: Couldn't open file on client side; trying server side: java.io.FileNotFoundException: No content provider:` 

FYI i'm trying to load 4 videos (each ~100kb) on my walkthrough component and only 2 of them are loading randomly. (on IOS everything works fine)


```
import Video from 'react-native-video';
var resolveAssetSource = require('react-native/Libraries/Image/resolveAssetSource');
...
...
...
  render() {
    let sourceVideo1 = resolveAssetSource(require('./video1.mp4')) || {};
    let sourceVideo2 = resolveAssetSource(require('./video2.mp4')) || {};
    let sourceVideo3 = resolveAssetSource(require('./video3.mp4')) || {};
    let sourceVideo4 = resolveAssetSource(require('./video4.mp4')) || {};
    return (
             ...
             ...
             <Video
              ref={(ref) => {
                this.firstPagePlayer = ref
              }}
              source={sourceVideo1}
              key="video1"
              resizeMode="cover"
              repeat={false} 
              playInBackground={false}
              playWhenInactive={false}
              style={[styles.image, {backgroundColor: 'white'}]}
            />
....

```

**Comment by jhen0409** [comment]
@el-lsan could you provide your react-native & Android version?

Also I [updated example](https://github.com/react-native-community/react-native-video/pull/429/commits/c3dd2a6d20f9aed2c5f88adede0e988c2497cc22), you can try it out.

**Comment by jhen0409** [comment]
I updated this PR, just use `drawable` instead of `raw` for `setRawData`. (See [`ResourceDrawableIdHelper` of Image usage](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/imagehelper/ResourceDrawableIdHelper.java#L54-L57), the assets file should in `drawable`)

**Comment by el-lsan** [comment]
@jhen0409 I'm using `"react-native": "^0.38"` and `Android 6`,
I also tested using latest RN `0.39.2`but still facing the same issue.

**Comment by jhen0409** [comment]
@el-lsan try print `identifier` with `Log`, if it is not 0, the problem may related to [ScalableVideoView](https://github.com/yqritc/Android-ScalableVideoView), I also have problem of video load in the emulator.

**Comment by jhen0409** [comment]
Resolved the conflict and also fix `android-exoplayer` part.

@mattapperson

File: Video.js [hunk 1]
```diff
@@ -180,7 +180,7 @@ export default class Video extends Component {
         uri,
         isNetwork,
         isAsset,
-        type: source.type,
+        type: source.type || 'mp4',
```
Comment (jhen0409) [inline Video.js]: It looks removed by #426 (See [this](https://github.com/react-native-community/react-native-video/pull/426/files#diff-2a97390647ad4fd466bccc2c92e7864eL165)), but it will broken native prop update (if it is `undefined`), so I added back it.

Comment (AndrewJack) [reply Video.js]: The exoplayer implementation can infer the type of video, but can be overridden by the `type` field.
By adding a default value the player doesn't infer the `type` and just assumes it is mp4, and playback fails if it isn't mp4.

Could we make this an empty string instead?

Comment (jhen0409) [reply Video.js]: @AndrewJack OK, will change to empty string. :)

**Comment by robbue** [comment]
Is this ready to be merged?

**Comment by krailler** [comment]
I need this fix.

**Comment by tarunmehta-quovantis** [comment]
Did any one find how to resolve this issue ?
