### PR TITLE
Fix/track selection by title

### LINKED ISSUE #2783: I want to change subtitle and audio track on run time please help, how we can do this
# i am unable to change subtitle and audio track on run time 
Please let me know how we can achieve this. 
 i am able to integrate subtitle with mp4 but not with .m3u8 or hls or mpd formates.

### LINKED ISSUE #4069: [ANDROID] Subtitle not working even after exoplayer became default
### Version

^6.4.3

### What platforms are you having the problem on?

Android

### System Version

0.74.0

### On what device are you experiencing the issue?

Real device, Simulator

### Architecture

New architecture with interop layer

### What happened?

 Subtitle not working even after exoplayer became default in android, but in IOS working perfectly.
code : 
  textTracks={[
                  {
                    title: 'English CC',
                    language: 'en',
                    type: 'text/vtt',
                     uri: 'https://bitdash-a.akamaihd.net/content/sintel/subtitles/subtitles_en.vtt',
                  },
                ]}
                selectedTextTrack={{
                  type: showFullScreen ? 'title' : 'disabled',
                  value: showFullScreen ? 'English CC' : '',
                }}

versions:
 "react-native": "0.74.0"
 "react-native-video": "^6.4.3",

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are: 
1. install the latest package 
2. added textTracks & selectedTextTrack props in Video

### PR DESCRIPTION
**Pull request by freeboub**
## Summary
Fix track selection by tile

### Motivation
fix: https://github.com/TheWidlarzGroup/react-native-video/issues/4069

### Changes
fix test on android to select by title: id was used but title reported is the label
Improve sample implementation to make it selection by title testable

## Test plan
Can be tested with the sample now after changing manually: textTracksSelectionBy

### CODE REVIEW

File: examples/basic/src/constants/general.ts [hunk 1]
```diff
@@ -2,13 +2,14 @@ import {
...
   ISO639_1,
+  SelectedTrackType,
   TextTrackType,
 } from 'react-native-video';
 import {SampleVideoSource} from '../types';
 import {localeVideo} from '../assets';
 import {Platform} from 'react-native';
 
-export const textTracksSelectionBy = 'index';
+export const textTracksSelectionBy = SelectedTrackType.INDEX;
```
Comment (freeboub) [inline examples/basic/src/constants/general.ts:16]:
```suggestion
// This constant allows to change how the sample behaves regarding to texts selection.
// You can change it to change how selector will use tracks information.
// by default, index will be displayed and index will be applied to selected tracks.
// You can also use LANGUAGE or TITLE 
export const textTracksSelectionBy = SelectedTrackType.INDEX;
```

**Review by seyedmostafahasani — APPROVED** [review]
