### PR TITLE
fix(ios): ensure onBandwidthUpdate is reported only when value change

### LINKED ISSUE #4139: [BUG]: onBandwidthUpdate not working on iOS
### Version

6.4.5

### What platforms are you having the problem on?

iOS

### System Version

17.4

### On what device are you experiencing the issue?

Simulator

### Architecture

Old architecture

### What happened?

onBandwidthUpdate is not logging anything on iOS. It works on android.
This is the portion of code:

`<Video
        ref={videoPlayer}
        style={styles.video}
        isLooping
        resizeMode="contain"
        paused={paused}
        onEnd={onEnd}
        onLoad={onLoad}
        onProgress={onProgress}
        onBandwidthUpdate={e => {
          console.log(Platform.OS, 'bandwidth', e);
        }}
        source={{
          uri: episode.videos[0].video,
        }}
      />`

I am using HLS streaming (index.m3u8) file. Does that change anything? Is there any setting or permission i should turn on or request from app connect

### Reproduction Link

_No response_

### Reproduction

Try onBandwidthUpdate prop in react-native-video.

### PR DESCRIPTION
**Pull request by freeboub**
## Summary
while testing: https://github.com/TheWidlarzGroup/react-native-video/issues/4146 on ios I saw the onBandwidthUpdate flooding app with the same value.

### Motivation
do not report multiple time the same value with onBandwidthUpdate
complementary fix for: https://github.com/TheWidlarzGroup/react-native-video/issues/4139

### Changes
Just avoid reporting multiple times the same value

## Test plan
can be tested with the sample

### CODE REVIEW

File: ios/Video/RCTVideo.swift [hunk 1]
```diff
@@ -63,6 +63,7 @@ class RCTVideo: UIView, RCTVideoPlayerViewControllerDelegate, RCTPlayerObserverH
     private var _presentingViewController: UIViewController?
     private var _startPosition: Float64 = -1
     private var _showNotificationControls = false
+    private var _lastBitrate = -2.0
```
Comment (seyedmostafahasani) [inline ios/Video/RCTVideo.swift:67]: I think it's better to set it to `-1.0` like `_startPosition` because a new developer working on the library might be confused if it's set to `-2.0`.
WDYT?

Comment (freeboub) [reply ios/Video/RCTVideo.swift:67]: Yes, In fact this is intended, but I will add comment. Apperently, AVPlayer sometime report -1 (not sure why), If I initilize the value to -1, this value will be missed !

Comment (freeboub) [inline ios/Video/RCTVideo.swift:67]:
```suggestion
    // Buffer last bitrate value received. Initialized to -2 to ensure -1 (sometimes reported by AVPlayer) is not missed
    private var _lastBitrate = -2.0
```

**Review by seyedmostafahasani — APPROVED** [review]

File: ios/Video/RCTVideo.swift (hunk 1 above)
Comment (seyedmostafahasani) [reply ios/Video/RCTVideo.swift:67]: Thanks @freeboub
It's better.

**Comment by freeboub** [comment]
@KrzysztofMoch any clue on this build issue ?
I think it is again cache problem, it would be great that you explain to me how to fix it (offline).
Thanks

**Review by KrzysztofMoch — APPROVED** [review]
Look fine for me

**Comment by anthonychemaly** [comment]
Please recheck the changes. OnBandwidthUpdate works on ios on mp4 file but is not working on HLS .m3u8
Kindly test on the file provided in the examples/basic: 

https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master_928.m3u8

on mp4, it indeed returns a bitrate. however, onBandwidthUpdate always returns -1 on HLS files. Anything I'm missing here @freeboub @KrzysztofMoch
