### PR TITLE
fix(ios): Do not crash when accessLog return nil

### LINKED ISSUE #3424: (IOS) App Freeze on handleAVPlayerAccess function [v6.0.0-beta.2]
# Bug

I'm the developer of the app SoSkills, video sharing app in gaming available on Apple and Android.
I saw there's some updates on this package and i have decided to upgrade it from v6.0.0-alpha.7 to v6.0.0-beta.2 in order to get fix, update and improvment.
After some tests, i have just met one big issue where the app was freezing, note that i let you some screenshots with clear error message, maybe it can help in order to have a stable version.

## Platform
IOS

## Environment info

Library version: v6.0.0-beta.2
Device: Iphone 12 pro max

## Steps To Reproduce

Create a FlatList with some videos, swipe (during the process stop the old video, start the new one and so on). After some swipe the library will crash. I want to let you know one more time that v6.0.0-alpha.7 is working fine.

## Expected behaviour

React Native video not freezing at all
Screenshot 2023-12-17 at 11 40 57
Screenshot 2023-12-17 at 11 41 08
Screenshot 2023-12-17 at 17 05 32

### PR DESCRIPTION
**Pull request by gkueny**
## Summary

accessLog method can return nil if no logging information are currently available (see https://developer.apple.com/documentation/avfoundation/avplayeritem/1388499-accesslog).

### Motivation

should fix https://github.com/react-native-video/react-native-video/issues/3424

### Changes

I handle the case where `accessLog` return `nil` & do not call onVideoBandwidthUpdate if it's `nil`. That should avoid some crash.

## Test plan

Sadly I can not reproduce the crash. I did not find a way to trigger `onVideoBandwidthUpdate`. Someone maybe can point me a way to reproduce this beahavior ?

### CODE REVIEW

**Comment by douzal34** [comment]
I have tested his branch and my issue from #3424 is not freezing anymore.
Great job @gkueny !

File: ios/Video/RCTVideo.swift [hunk 1]
```diff
@@ -1375,9 +1375,12 @@ class RCTVideo: UIView, RCTVideoPlayerViewControllerDelegate, RCTPlayerObserverH
...
     func handleAVPlayerAccess(notification: NSNotification!) {
         let accessLog: AVPlayerItemAccessLog! = (notification.object as! AVPlayerItem).accessLog()
-        let lastEvent: AVPlayerItemAccessLogEvent! = accessLog.events.last
 
-        onVideoBandwidthUpdate?(["bitrate": lastEvent.observedBitrate, "target": reactTag])
+        if accessLog != nil {
+            let lastEvent: AVPlayerItemAccessLogEvent! = accessLog.events.last
+
+            onVideoBandwidthUpdate?(["bitrate": lastEvent.observedBitrate, "target": reactTag])
+        }
```
Comment (KrzysztofMoch) [inline ios/Video/RCTVideo.swift]: Let's make this more elegant:
```swift
    @objc
    func handleAVPlayerAccess(notification: NSNotification!) {
        guard let accessLog = (notification.object as? AVPlayerItem)?.accessLog() else {
            return
        }

        guard let lastEvent = accessLog.events.last else { return }
        onVideoBandwidthUpdate?(["bitrate": lastEvent.observedBitrate, "target": reactTag])
    }
  ```

**Review by KrzysztofMoch — CHANGES_REQUESTED** [review]
Thank you! I left one small comment, but it looks good

**Comment by gkueny** [comment]
@KrzysztofMoch thanks for the review.

> I did not find a way to trigger onVideoBandwidthUpdate. Someone maybe can point me a way to reproduce this beahavior ?

For my own knowledge, do you know how I can trigger `AVPlayerItemNewAccessLogEntry` notification ?

**Review by freeboub — APPROVED** [review]

**Review by KrzysztofMoch — APPROVED** [review]
@gkueny I am not sure... 😅 - it's sometimes just work for me
