### PR TITLE
fix(ios): call `onLoadStart` earlier

### LINKED ISSUE #3744: onBuffer & onLoadStart not working properly
### Version

react-native-video: 6.0.0-rc.0

### What platforms are you having the problem on?

iOS

### What happened?

In android everything working fine, But in IOS onBuffer not working & onLoadStart fired with onLoad

### PR DESCRIPTION
**Pull request by KrzysztofMoch**
## Summary
call callback `onLoadStart` earlier to make it work properly 

### Motivation
fix #3744

### Changes
- move callback `onLoadStart` earlier
- don't call `onVideoBuffer` in `handlePlaybackLikelyToKeepUp` if value is same as previous

## Test plan
- [x] Tested Locally
- [x] CI pass

### CODE REVIEW

File: ios/Video/RCTVideo.swift [hunk 1]
```diff
@@ -1434,7 +1435,11 @@ class RCTVideo: UIView, RCTVideoPlayerViewControllerDelegate, RCTPlayerObserverH
     }
 
     // Continue playing (or not if paused) after being paused due to hitting an unbuffered zone.
-    func handlePlaybackLikelyToKeepUp(playerItem _: AVPlayerItem, change _: NSKeyValueObservedChange<Bool>) {
```
Comment (freeboub) [inline ios/Video/RCTVideo.swift:1437]: I am not sure this will be enough as there are 2 other calls in handleReadyForDisplay and handlePlaybackBufferKeyEmpty.
I think the buffering state shall handled with a local variable to know what is the oldState reported to the UI, and not the old handlePlaybackLikelyToKeepUp

**Comment by freeboub** [comment]
I think this change may also fix: https://github.com/TheWidlarzGroup/react-native-video/issues/3675

File: ios/Video/RCTVideo.swift (hunk 1 above)
Comment (KrzysztofMoch) [reply ios/Video/RCTVideo.swift:1437]: Grate Idea! this is working perfect now

**Review by freeboub — APPROVED** [review]
