### PR TITLE
fix(sample): update dependencies to fix local asset playback

### LINKED ISSUE #4120: [BUG]: Sample on expo cannot play local file
### Version

6.3.4

### What platforms are you having the problem on?

iOS, Android

### System Version

N/A

### On what device are you experiencing the issue?

Real device, Simulator

### Architecture

Old architecture

### What happened?

The sample cannot play local file.
The issue started with expo update.

### Reproduction Link

repository link

### Reproduction

Step to reproduce this bug are: 
Just launch sample app, the 2 first local contents cannot be played

### PR DESCRIPTION
**Pull request by freeboub**
## Summary
Fix playback of local assets broken since expo move in the sample

### Motivation
Fix: https://github.com/TheWidlarzGroup/react-native-video/issues/4120

### Changes
Just upgrade sample dependencies (and upgrade expo in the same time)
The Root cause of the issue was due to react native windows version. 
As described in the ticket @react-native/assets-registry was duplicated
One version from react native and one version for react native winwdows.
Fix react-native-windows version ensure the module is not downloaded twice 

## Test plan
Can be tested in the sample

### CODE REVIEW

File: ios/Video/RCTVideo.swift [hunk 1]
```diff
@@ -284,9 +284,18 @@ class RCTVideo: UIView, RCTVideoPlayerViewControllerDelegate, RCTPlayerObserverH
...
+            let isExternalPlaybackActive = false
+        #else
+            let isExternalPlaybackActive = _player?.isExternalPlaybackActive ?? false
+        #endif
+        return isExternalPlaybackActive
+    }
+
     @objc
     func applicationWillResignActive(notification _: NSNotification!) {
-        let isExternalPlaybackActive = _player?.isExternalPlaybackActive ?? false
```
Comment (freeboub) [inline ios/Video/RCTVideo.swift]: I didn't start from master branch 😢

**Review by seyedmostafahasani — APPROVED** [review]

**Review by KrzysztofMoch — APPROVED** [review]
