### PR TITLE
fix(android): allow chunk less preparation

### LINKED ISSUE #3766: [BUG]: 608/708 captions in HLS source not recognized by the player
### Version

^6.0.0-beta.8

### What platforms are you having the problem on?

Android

### Architecture

Old architecture

### What happened?

608/708 captions within an HLS source aren't recognized by the player, onTextTracks never triggers.

### Reproduction

repository link

### Reproduction

Ran on an android emulator on a windows PC.

Step to reproduce this bug are: 
Set up a basic app with the player, with HLS sources enabled.
Set source to an HLS playlist with embedded 608/708 captions
608/708 tracks are never found, onTextTracks never triggers

### PR DESCRIPTION
**Pull request by freeboub**
## Summary
Add missing textTracksAllowChunklessPreparation forwarding in Video.js
fix internal typo

### Motivation
Fix: https://github.com/TheWidlarzGroup/react-native-video/issues/3766

### CODE REVIEW

**Review by KrzysztofMoch — APPROVED** [review]

File: android/src/main/java/com/brentvatne/common/api/Source.kt [hunk 1]
```diff
@@ -123,7 +123,7 @@ class Source {
         private const val PROP_SRC_TYPE = "type"
         private const val PROP_SRC_METADATA = "metadata"
         private const val PROP_SRC_HEADERS = "requestHeaders"
-        private const val PROP_SRC_TEXT_TRACKS_ALLOW_CHUNCKLESS_PREPARATION = "textTracksAllowChunklessPreparation"
+        private const val PROP_SRC_TEXT_TRACKS_ALLOW_CHUNKLESS_PREPARATION = "textTracksAllowChunclessPreparation"
```
Comment (freeboub) [inline android/src/main/java/com/brentvatne/common/api/Source.kt]:
```suggestion
        private const val PROP_SRC_TEXT_TRACKS_ALLOW_CHUNKLESS_PREPARATION = "textTracksAllowChunklessPreparation"
```
