### PR TITLE
fix(android):  show the status bar and navigation bar after exiting f…

### LINKED ISSUE #4047: [BUG]: Android navigation bar stays hidden after video using fullscreen no longer mounted
### Version

6.4.3

### What platforms are you having the problem on?

Android

### System Version

Android 13

### On what device are you experiencing the issue?

Simulator

### Architecture

Old architecture

### What happened?

After playing the video or closing the screen with the video using `fullscreen={true}`, the status bar reappears but the navigation bar doesn't.

Maybe it is related to [this issue](https://github.com/TheWidlarzGroup/react-native-video/pull/3978).

### Reproduction

_No response_

### Reproduction

Step to reproduce this bug are:
- Show a screen with Video component with `fullscreen={true}`
- Close the screen

### PR DESCRIPTION
**Pull request by seyedmostafahasani**
…ull-screen mode

### Motivation
Fix #4047, #4107

## Test plan

### CODE REVIEW

File: android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java [hunk 1]
```diff
@@ -2266,10 +2266,6 @@ public void setFullscreen(boolean fullscreen) {
                 fullScreenPlayerView.show();
             }
             UiThreadUtil.runOnUiThread(() -> {
-                originalFitsSystemWindows = window.getDecorView().getFitsSystemWindows();
```
Comment (freeboub) [inline android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java:2269]: but why did you remove this code ?

File: android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java [hunk 2]
```diff
@@ -2280,8 +2276,7 @@ public void setFullscreen(boolean fullscreen) {
                 setControls(controls);
             }
             UiThreadUtil.runOnUiThread(() -> {
-                WindowCompat.setDecorFitsSystemWindows(window, originalFitsSystemWindows);
```
Comment (freeboub) [inline android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java:2283]: and this code also ?!

File: android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java (hunk 1 above)
Comment (seyedmostafahasani) [reply android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java:2269]: I have decided to remove the system window handling code `(fitsSystemWindows and WindowCompat.setDecorFitsSystemWindows)` because fullscreen mode is entirely managed within a Dialog. Since the dialog controls how the UI behaves in fullscreen mode, we no longer need to manually adjust the system windows at the activity level when entering or exiting fullscreen. The dialog itself will handle all necessary UI changes, including the display and behavior of system bars. Therefore, maintaining redundant fullscreen handling in the activity is unnecessary.

File: android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java (hunk 2 above)
Comment (seyedmostafahasani) [reply android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java:2283]: The above reason.

File: android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java (hunk 1 above)
Comment (freeboub) [reply android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java:2269]: So you don't need to add line: controller.setSystemBarsBehavior(WindowInsetsControllerCompat.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE);
?

Comment (seyedmostafahasani) [reply android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java:2269]: Exactly 
I will remove it.

Comment (seyedmostafahasani) [reply android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java:2269]: @freeboub 
I removed it.

**Review by freeboub — APPROVED** [review]

**Comment by seyedmostafahasani** [comment]
@KrzysztofMoch @YangJonghun 
If you have enough time please check out this PR.

**Comment by freeboub** [comment]
@KrzysztofMoch Are you OK to merge this PR ?

**Review by KrzysztofMoch — APPROVED** [review]
Yes
