### PR TITLE
fix(ios): fix sideloading external subtitles

### LINKED ISSUE #3642: [BUG]: basic sample project in repo on iOS doesn't show textTracks
### Version

v6 (Beta)

### What platforms are you having the problem on?

iOS

### Architecture

Old architecture

### What happened?

I ran the basic sample app (on `master`) and was trying to find a working example of the textTracks on iOS since I can't get it to work on my own sample repo.
I expected to see subtitles/captions since the title of this one says subtitles.

Screenshot 2024-04-02 at 2 43 02 PM

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are: 
1. Run `git clean -xdf && yarn xbasic install && cd examples/basic/ios && pod install && cd - && yarn xbasic ios`*
* At this point I noticed my `Podfile.lock` had some differences with git diff `COCOAPODS: 1.15.2`
2. Click channel up until reaches 'sintel with sideLoaded subtitles', watch until audio occurs.

Observe no captions/subtitles.

### PR DESCRIPTION
**Pull request by KrzysztofMoch**
## Summary
Fixed sideloading external subtitles

### Motivation
fixes #3642

### Changes
- updated `getValidTextTracks` impl

## Test plan
- [x] Tested locally
- [x] CI passes

### CODE REVIEW

File: examples/basic/src/VideoPlayer.tsx [hunk 1]
```diff
@@ -135,7 +135,9 @@ class VideoPlayer extends Component {
     },
     {
       description: 'sintel with sideLoaded subtitles',
```
Comment (freeboub) [inline examples/basic/src/VideoPlayer.tsx]:
```suggestion
      description: 'BigBugBunny sideLoaded subtitles',
```

File: examples/basic/src/VideoPlayer.tsx [hunk 2]
```diff
@@ -135,7 +135,9 @@ class VideoPlayer extends Component {
...
-      uri: 'https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8', // this is sample video, my actual video file is MP4
+      // sideloaded subtitiles wont work for streaming like HLS
```
Comment (freeboub) [inline examples/basic/src/VideoPlayer.tsx]:
```suggestion
      // sideloaded subtitles wont work for streaming like HLS on ios
```

File: examples/basic/src/VideoPlayer.tsx [hunk 3]
```diff
@@ -363,11 +365,11 @@ class VideoPlayer extends Component {
 
   onPlaybackRateChange = (data: OnPlaybackRateChangeData) => {
     console.log('onPlaybackRateChange', data);
-  }
+  };
 
   onPlaybackStateChanged = (data: OnPlaybackStateChangedData) => {
     console.log('onPlaybackStateChanged', data);
-  }
+  };
```
Comment (freeboub) [inline examples/basic/src/VideoPlayer.tsx:372]: would make sense to lint the sample also :) but it is another topic ;)

**Review by freeboub — APPROVED** [review]

**Comment by freeboub** [comment]
minor proposal added, Thank you !
